"""C++ code templates for Min-DevKit external archetypes.

Provides render functions for three archetypes:
- Message/data: inlet<>/outlet<>/message<> with MIN_FUNCTION handlers
- DSP/signal: sample_operator<N,M> with operator() perform method
- Scheduler: timer<> with attribute<> for interval and start/stop toggle

Also provides CMakeLists.txt and Catch2 test scaffold templates.

All generated code uses Min-DevKit C++17 patterns exclusively
(no classic Max SDK class_new/class_addmethod patterns).
"""

from __future__ import annotations


def render_message_template(
    name: str,
    description: str,
    inlets: list[dict],
    outlets: list[dict],
    handlers: list[str],
) -> str:
    """Render C++ source for a message/data processing external.

    Args:
        name: External object name (valid C++ identifier).
        description: Human-readable description (used in MIN_DESCRIPTION).
        inlets: List of dicts with "comment" key for inlet descriptions.
        outlets: List of dicts with "comment" key for outlet descriptions.
        handlers: List of message handler names (e.g., "bang", "number", "list").

    Returns:
        Complete C++ source string.
    """
    # Build inlet declarations
    inlet_lines = []
    for i, inlet in enumerate(inlets):
        comment = inlet.get("comment", f"input {i + 1}")
        var_name = f"m_input_{i}" if i > 0 else "m_input"
        inlet_lines.append(
            f'    inlet<>  {var_name}  {{ this, "{comment}" }};'
        )

    # Build outlet declarations
    outlet_lines = []
    for i, outlet in enumerate(outlets):
        comment = outlet.get("comment", f"output {i + 1}")
        var_name = f"m_output_{i}" if i > 0 else "m_output"
        outlet_lines.append(
            f'    outlet<> {var_name} {{ this, "{comment}" }};'
        )

    # Build message handlers
    handler_lines = []
    for handler_name in handlers:
        var_name = f"m_{handler_name}"
        handler_lines.append(f"""    message<> {var_name} {{ this, "{handler_name}",
        MIN_FUNCTION {{
            // TODO: implement {handler_name} handler
            return {{}};
        }}
    }};""")

    inlets_str = "\n".join(inlet_lines)
    outlets_str = "\n".join(outlet_lines)
    handlers_str = "\n\n".join(handler_lines)

    return f'''#include "c74_min.h"

using namespace c74::min;

class {name} : public object<{name}> {{
public:
    MIN_DESCRIPTION {{ "{description}" }};
    MIN_TAGS {{ "utility" }};
    MIN_AUTHOR {{ "Generated by MAX Framework" }};

{inlets_str}

{outlets_str}

{handlers_str}
}};

MIN_EXTERNAL({name});
'''


def render_dsp_template(
    name: str,
    description: str,
    num_inputs: int,
    num_outputs: int,
    params: list[dict],
) -> str:
    """Render C++ source for a DSP/signal processing external.

    Args:
        name: External object name (valid C++ identifier).
        description: Human-readable description.
        num_inputs: Number of signal inputs.
        num_outputs: Number of signal outputs.
        params: List of param dicts with name, default, min, max.

    Returns:
        Complete C++ source string.
    """
    # Build signal inlet declarations
    inlet_lines = []
    for i in range(num_inputs):
        var_name = f"m_input_{i}" if i > 0 else "m_input"
        inlet_lines.append(
            f'    inlet<>  {var_name}  {{ this, "(signal) audio input {i + 1}" }};'
        )

    # Build signal outlet declarations
    outlet_lines = []
    for i in range(num_outputs):
        var_name = f"m_output_{i}" if i > 0 else "m_output"
        outlet_lines.append(
            f'    outlet<> {var_name} {{ this, "(signal) audio output {i + 1}", "signal" }};'
        )

    # Build attribute declarations for params
    param_lines = []
    for param in params:
        p_name = param["name"]
        p_default = param.get("default", 0.0)
        p_min = param.get("min", 0.0)
        p_max = param.get("max", 1.0)
        param_lines.append(
            f'    attribute<double> m_{p_name} {{ this, "{p_name}", {p_default},\n'
            f'        range {{ {p_min}, {p_max} }}\n'
            f'    }};'
        )

    # Build input parameter list for operator()
    input_params = ", ".join(f"sample input{i + 1}" for i in range(num_inputs))
    if num_inputs == 1:
        input_params = "sample input"

    inlets_str = "\n".join(inlet_lines)
    outlets_str = "\n".join(outlet_lines)
    params_str = "\n\n".join(param_lines)

    params_section = f"\n{params_str}\n" if params_str else ""

    return f'''#include "c74_min.h"

using namespace c74::min;

class {name} : public object<{name}>, public sample_operator<{num_inputs}, {num_outputs}> {{
public:
    MIN_DESCRIPTION {{ "{description}" }};
    MIN_TAGS {{ "audio" }};
    MIN_AUTHOR {{ "Generated by MAX Framework" }};

{inlets_str}

{outlets_str}
{params_section}
    samples<{num_outputs}> operator()({input_params}) {{
        // TODO: implement DSP processing
        return {{ input }};
    }};

    message<> dspsetup {{ this, "dspsetup",
        MIN_FUNCTION {{
            m_samplerate = args[0];
            return {{}};
        }}
    }};

private:
    double m_samplerate {{ 44100.0 }};
}};

MIN_EXTERNAL({name});
'''


def render_scheduler_template(
    name: str,
    description: str,
    interval_default: float,
    attributes: list[dict],
) -> str:
    """Render C++ source for a scheduler external.

    Args:
        name: External object name (valid C++ identifier).
        description: Human-readable description.
        interval_default: Default interval in ms.
        attributes: List of extra attribute dicts with name, type, default, min, max.

    Returns:
        Complete C++ source string.
    """
    # Build additional attribute declarations
    attr_lines = []
    for attr in attributes:
        a_name = attr["name"]
        a_type = attr.get("type", "double")
        a_default = attr.get("default", 0.0)
        a_min = attr.get("min", 0.0)
        a_max = attr.get("max", 1.0)
        attr_lines.append(
            f'    attribute<{a_type}> m_{a_name} {{ this, "{a_name}", {a_default},\n'
            f'        range {{ {a_min}, {a_max} }}\n'
            f'    }};'
        )

    extra_attrs = "\n\n".join(attr_lines)
    extra_attrs_section = f"\n{extra_attrs}\n" if extra_attrs else ""

    return f'''#include "c74_min.h"

using namespace c74::min;

class {name} : public object<{name}> {{
public:
    MIN_DESCRIPTION {{ "{description}" }};
    MIN_TAGS {{ "time" }};
    MIN_AUTHOR {{ "Generated by MAX Framework" }};

    inlet<>  m_input    {{ this, "(toggle) on/off" }};
    outlet<> m_bang_out  {{ this, "(bang) tick output" }};

    timer<> m_timer {{ this,
        MIN_FUNCTION {{
            m_bang_out.send("bang");
            m_timer.delay(m_interval);
            return {{}};
        }}
    }};

    attribute<double> m_interval {{ this, "interval", {interval_default},
        range {{ 1.0, 60000.0 }}
    }};
{extra_attrs_section}
    message<> m_toggle {{ this, "int",
        MIN_FUNCTION {{
            if (args[0] > 0)
                m_timer.delay(0);
            else
                m_timer.stop();
            return {{}};
        }}
    }};
}};

MIN_EXTERNAL({name});
'''


def render_cmake_template(name: str) -> str:
    """Render CMakeLists.txt for a Min-DevKit external project.

    Args:
        name: External project name.

    Returns:
        CMakeLists.txt content string.
    """
    return f'''cmake_minimum_required(VERSION 3.19)

# Set project name from directory
get_filename_component(PROJECT_NAME ${{CMAKE_CURRENT_SOURCE_DIR}} NAME)
project(${{PROJECT_NAME}})

# Find min-api
set(MIN_API_DIR "${{CMAKE_CURRENT_SOURCE_DIR}}/min-devkit/source/min-api")
if(NOT EXISTS "${{MIN_API_DIR}}")
    message(FATAL_ERROR "min-api not found. Run: git submodule update --init --recursive")
endif()

# Include min-api CMake scripts
include("${{MIN_API_DIR}}/script/min-pretarget.cmake")

# Define source files
set(SOURCE_FILES
    ${{CMAKE_CURRENT_SOURCE_DIR}}/source/${{PROJECT_NAME}}.cpp
)

# Create the external
add_library(${{PROJECT_NAME}} MODULE ${{SOURCE_FILES}})

# Apply min-api post-target configuration
include("${{MIN_API_DIR}}/script/min-posttarget.cmake")
'''


def render_test_template(name: str) -> str:
    """Render a basic Catch2 test scaffold for an external.

    Args:
        name: External object name.

    Returns:
        C++ test source string.
    """
    return f'''#include "c74_min_api.h"

#include "c74_min.h"

#include "{name}.cpp"

#include <catch.hpp>

TEST_CASE("{name} responds to bang", "[{name}]") {{
    ext_main(nullptr);  // register the external

    // TODO: add test assertions
    REQUIRE(true);
}}
'''
