"""Override merger: transforms proposed audit overrides into production overrides.json.

Reads proposed-overrides.json (generated by the audit pipeline), detects conflicts
with existing manual overrides, applies field-level conflict resolution, groups
entries by domain with separator keys, and writes an idempotent overrides.json.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path

from src.maxpat.db_lookup import ObjectDatabase

# Domain ordering for grouping in overrides.json
DOMAIN_ORDER = ["max", "msp", "jitter", "mc", "gen", "m4l", "rnbo", "packages", "other"]

# Canonical display labels for domain header comments
_DOMAIN_LABELS = {
    "max": "Max Objects",
    "msp": "MSP Objects",
    "jitter": "Jitter Objects",
    "mc": "MC Objects",
    "gen": "Gen Objects",
    "m4l": "Max for Live Objects",
    "rnbo": "RNBO Objects",
    "packages": "Package Objects",
    "other": "Other Objects (not in domain JSONs)",
}


class OverrideMerger:
    """Merges proposed audit overrides into the production overrides.json.

    Handles: confidence filtering, conflict detection/resolution,
    domain grouping, audit metadata insertion, manual entry preservation.
    Idempotent -- running twice with the same inputs produces the same result.
    """

    def __init__(
        self,
        proposed_path: Path,
        overrides_path: Path,
        db: ObjectDatabase,
    ) -> None:
        """Initialize with paths to proposed and existing overrides files.

        Args:
            proposed_path: Path to proposed-overrides.json (audit output).
            overrides_path: Path to existing overrides.json (production file).
            db: ObjectDatabase instance for domain lookups.
        """
        self._proposed = json.loads(proposed_path.read_text())
        self._existing = json.loads(overrides_path.read_text())
        self._overrides_path = overrides_path
        self._db = db

    def detect_conflicts(self) -> dict[str, dict]:
        """Return the conflict entries from the proposed overrides file.

        Each conflict has audit_proposed, existing_manual, and reason keys.

        Returns:
            Dict mapping object name to conflict info. Empty dict if no conflicts.
        """
        return dict(self._proposed.get("conflicts", {}))

    def merge(self, conflict_resolutions: dict | None = None) -> dict:
        """Execute the merge and return the new overrides dict.

        Merges all non-conflict proposals into the existing overrides, resolves
        conflicts per the provided field-level instructions, groups objects by
        domain with separator headers, and preserves version_map and
        variable_io_rules sections.

        Args:
            conflict_resolutions: Dict mapping object name to resolution
                instructions. Each value is a dict with "adopt_fields" key
                listing fields to take from the audit side. Fields not listed
                are preserved from the manual entry. None or missing entries
                mean the conflict is not resolved (existing manual entry is
                kept as-is).

        Returns:
            The complete merged overrides dict ready for writing.
        """
        if conflict_resolutions is None:
            conflict_resolutions = {}

        # Start with deep copy of existing file to preserve all top-level sections
        merged = copy.deepcopy(self._existing)

        # Collect all objects that will be in the merged file
        all_objects: dict[str, dict] = {}

        # 1. Preserve existing manual entries (non-conflict ones stay as-is)
        conflict_names = set(self._proposed.get("conflicts", {}).keys())
        existing_objects = self._existing.get("objects", {})
        for name, entry in existing_objects.items():
            if name.startswith("_"):
                continue  # skip domain headers or metadata from previous merges
            all_objects[name] = copy.deepcopy(entry)

        # 2. Add non-conflict proposed entries (all confidence tiers)
        for name, entry in self._proposed.get("objects", {}).items():
            obj_entry = copy.deepcopy(entry)

            # Flag orphan objects not in any domain JSON
            if not self._db.exists(name):
                obj_entry["_note"] = (
                    "No base domain entry -- override inactive until "
                    "object added to domain JSON"
                )

            all_objects[name] = obj_entry

        # 3. Handle conflicts
        for name, conflict in self._proposed.get("conflicts", {}).items():
            if name in conflict_resolutions:
                # Resolve: start from manual entry, adopt specified fields from audit
                resolution = conflict_resolutions[name]
                adopt_fields = resolution.get("adopt_fields", [])

                manual_entry = copy.deepcopy(
                    existing_objects.get(name, conflict.get("existing_manual", {}))
                )
                audit_entry = conflict.get("audit_proposed", {})

                resolved = copy.deepcopy(manual_entry)
                resolved["_manual_original"] = copy.deepcopy(manual_entry)

                for field in adopt_fields:
                    if field in audit_entry:
                        resolved[field] = copy.deepcopy(audit_entry[field])

                # Add audit metadata
                if "_audit" in audit_entry:
                    resolved["_audit"] = copy.deepcopy(audit_entry["_audit"])

                all_objects[name] = resolved
            else:
                # Unresolved conflict: keep existing manual entry as-is
                # (already in all_objects from step 1)
                pass

        # 4. Group by domain with separator headers
        grouped = self._group_by_domain(all_objects)

        # Replace the objects section with grouped result
        merged["objects"] = grouped

        return merged

    def write(self, merged: dict) -> None:
        """Write the merged overrides dict to disk.

        Writes as pretty-printed JSON (indent=2) with trailing newline.

        Args:
            merged: The complete merged overrides dict.
        """
        self._overrides_path.write_text(
            json.dumps(merged, indent=2) + "\n"
        )

    def _get_domain(self, obj_name: str) -> str:
        """Get the domain string for an object.

        Uses db.lookup() to find the domain. Falls back to 'other' if the
        object is not in any domain JSON.

        Args:
            obj_name: Object name to look up.

        Returns:
            Domain string (e.g., 'msp', 'max', 'jitter', 'other').
        """
        obj = self._db.lookup(obj_name)
        if obj is None:
            return "other"

        domain = obj.get("domain", obj.get("module", ""))
        if not domain:
            return "other"

        # Normalize domain names to lowercase short forms
        domain_lower = domain.lower()

        # Map known full names to short forms
        domain_map = {
            "max": "max",
            "msp": "msp",
            "jitter": "jitter",
            "mc": "mc",
            "gen": "gen",
            "m4l": "m4l",
            "rnbo": "rnbo",
            "packages": "packages",
        }

        for key, value in domain_map.items():
            if key in domain_lower:
                return value

        return "other"

    def _group_by_domain(self, objects: dict[str, dict]) -> dict:
        """Group override entries by domain with separator keys.

        Objects are sorted alphabetically within each domain group.
        Domains appear in the standard order: max, msp, jitter, mc, gen,
        m4l, rnbo, packages, other.

        Args:
            objects: Flat dict of object name -> override entry.

        Returns:
            Ordered dict with _domain_* separator keys between groups.
        """
        # Bucket objects by domain
        buckets: dict[str, dict[str, dict]] = {d: {} for d in DOMAIN_ORDER}

        for name, entry in objects.items():
            domain = self._get_domain(name)
            if domain not in buckets:
                domain = "other"
            buckets[domain][name] = entry

        # Build grouped dict with separators
        grouped: dict = {}
        for domain in DOMAIN_ORDER:
            domain_objects = buckets.get(domain, {})
            if not domain_objects:
                continue
            label = _DOMAIN_LABELS.get(domain, f"{domain.upper()} Objects")
            grouped[f"_domain_{domain}"] = f"--- {label} ---"
            # Sort objects alphabetically within domain
            for name in sorted(domain_objects.keys()):
                grouped[name] = domain_objects[name]

        return grouped
